---
jobs:
  _:
    name: Require “Allow Edits”
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          allowed-endpoints: api.github.com:443
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ljharb/require-allow-edits@main
name: Require “Allow Edits”
'on': [pull_request_target]