---
jobs:
  shellcheck:
    needs: [shellcheck_matrix]
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          egress-policy: block
      - run: echo tests completed
  shellcheck_matrix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          allowed-endpoints: ghcr.io:443 github.com:443 pkg-containers.githubusercontent.com:443
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - env:
          HOMEBREW_NO_ANALYTICS: 1
        name: Install latest shellcheck
        run: brew install shellcheck
      - run: which shellcheck
      - run: shellcheck --version
      - name: Run shellcheck on ${{ matrix.file }}
        run: shellcheck -s ${{ matrix.shell }} ${{ matrix.file }}
    strategy:
      fail-fast: false
      matrix:
        file:
          - nvm.sh
        include:
          - file: install.sh
            shell: bash
          - file: bash_completion
            shell: bash
          - file: nvm-exec
            shell: bash
        shell:
          - bash
          - sh
          - dash
          - ksh
name: 'Tests: shellcheck'
'on': [pull_request, push]