---
env:
  NVM_INSTALL_GITHUB_REPO: ${{ github.repository }}
  NVM_INSTALL_VERSION: ${{ github.sha }}
jobs:
  cygwin_matrix:
    continue-on-error: true
    name: Cygwin nvm install
    permissions:
      contents: none
    runs-on: windows-latest
    steps:
      - name: Install Cygwin
        run: |
          export SITE='https://mirror.clarkson.edu/cygwin/' # see https://archlinux.org/mirrors/clarkson.edu/1603/ for uptime status
          export SITE='https://mirrors.kernel.org/sourceware/cygwin/'
          export LOCALDIR="$(pwd)"
          export ROOTDIR="$USERPROFILE\\cygwin"
          export PACKAGES='bash,git,curl'

          curl -fsSLo setup-x86_64.exe 'https://cygwin.com/setup-x86_64.exe'
          ./setup-x86_64.exe --disable-buggy-antivirus -q -s "$SITE" -l "$LOCALDIR" -R "$ROOTDIR" -P "$PACKAGES"

          cat >~/setup.sh <<EOM
            unset npm_config_prefix
            export NVM_INSTALL_GITHUB_REPO="$NVM_INSTALL_GITHUB_REPO"
            export NVM_INSTALL_VERSION="$NVM_INSTALL_VERSION"

            curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | bash
            . "$HOME/.nvm/nvm.sh"
            nvm install --lts

            nvm deactivate
            rm -rf "$HOME/.nvm/nvm.sh"

            curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | METHOD=script bash
            . "$HOME/.nvm/nvm.sh"
            nvm install 9
          EOM
        shell: bash
      - name: Retrieve nvm
        run: |
          cd %USERPROFILE%\cygwin\bin
          bash.exe "%USERPROFILE%\setup.sh"

        shell: cmd
  msys_fail_install:
    name: MSYS fail prefix nvm install
    permissions:
      contents: none
    runs-on: windows-latest
    steps:
      - name: Retrieve nvm
        run: |
          curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | METHOD=script bash
          . "$HOME/.nvm/nvm.sh"
          ! nvm install --lts
        shell: bash
  msys_matrix:
    name: MSYS nvm install
    permissions:
      contents: none
    runs-on: windows-latest
    steps:
      - name: Retrieve nvm
        run: |
          unset npm_config_prefix
          if [ "${{ matrix.npm-node-version }}" = "--lts" ]; then curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | bash else curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | METHOD=script bash fi . "$HOME/.nvm/nvm.sh" nvm install ${{ matrix.npm-node-version }}
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        npm-node-version:
          - '--lts'
          - '--default 12'
          - '--no-progress 10'
  nvm_windows:
    name: tests, on windows
    needs: [wsl_matrix, wsl_matrix_unofficial, cygwin_matrix, msys_matrix, msys_fail_install]
    # Default installation does not work due to npm_config_prefix set to C:\npm\prefix
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - run: echo tests completed
  wsl_matrix:
    continue-on-error: true
    defaults:
      run:
        shell: wsl-bash {0}
    env:
      WSLENV: NVM_INSTALL_GITHUB_REPO:NVM_INSTALL_VERSION:/p
    name: WSL nvm install
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v2
        with:
          additional-packages: bash git curl ca-certificates wget
          distribution: ${{ matrix.wsl-distrib }}
      - name: Retrieve nvm on WSL
        run: |
          if [ -z "${{ matrix.method }}" ]; then curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | bash else curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | METHOD="${{matrix.method}}" bash fi . "$HOME/.nvm/nvm.sh" nvm install ${{ matrix.npm-node-version }} node -v
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - npm-node-version: '--lts'
            wsl-distrib: Ubuntu-18.04
          - npm-node-version: '21'
            wsl-distrib: Ubuntu-18.04
          - npm-node-version: '18'
            wsl-distrib: Ubuntu-18.04
        method:
          - ''
          - script
        npm-node-version:
          - '--lts'
          - '21'
          - '18'
          - '16'
          - '14'
          - '12'
          - '10'
        wsl-distrib:
          - Debian
        # - Alpine # fails
          - Ubuntu-20.04
          - Ubuntu-18.04
  wsl_matrix_unofficial:
    continue-on-error: true
    defaults:
      run:
        shell: wsl-bash {0}
    env:
      NVM_NODEJS_ORG_MIRROR: https://unofficial-builds.nodejs.org/download/release
      WSLENV: NVM_INSTALL_GITHUB_REPO:NVM_INSTALL_VERSION:/p
    name: WSL nvm install
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v2
        with:
          additional-packages: bash git curl ca-certificates wget
          distribution: ${{ matrix.wsl-distrib }}
      - name: Retrieve nvm on WSL
        run: |
          if [ -z "${{ matrix.method }}" ]; then curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | bash else curl -fsSLo- "https://raw.githubusercontent.com/${NVM_INSTALL_GITHUB_REPO}/${NVM_INSTALL_VERSION}/install.sh" | METHOD="${{matrix.method}}" bash fi . "$HOME/.nvm/nvm.sh" NVM_NODEJS_ORG_MIRROR=${{ env.NVM_NODEJS_ORG_MIRROR }} nvm install ${{ matrix.npm-node-version }}
    strategy:
      fail-fast: false
      matrix:
        method:
          - ''
          - script
        npm-node-version:
          - '--lts'
          - '21'
          - '18'
          - '16'
          - '14'
          - '12'
          - '11'
          - '10'
        wsl-distrib:
          - Alpine
name: 'Tests on Windows: `nvm install`'
'on': [pull_request, push]